<a href="https://colab.research.google.com/github/prashanthi-r/capstone/blob/master/linearReg.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import pandas as pd
from sklearn.datasets import load_boston 
from sklearn.model_selection import train_test_split
import random
import math
import warnings

In [ ]:
warnings.filterwarnings("ignore", category=RuntimeWarning)

In [ ]:
weights = [1.65921924,1.62628418]
bias = 0.96367349
# bias = 0.0

In [ ]:
x_train = [[4,1],[2,8],[1,0],[3,2],[1,4],[6,7]]
y_train=[2,-14,1,-1,-7,-8]
# x_train=[[1,4],[1,0],[6,7],[3,2],[4,1],[2,8]]
# y_train=[-7,1,-8,-1,2,-14]

In [ ]:
print(len(x_train))
print(len(y_train))
print(x_train[4])
print(y_train[4])

6
6
[1, 4]
-7


In [ ]:
print(weights)
print(bias)

[1.65921924, 1.62628418]
0.96367349


In [ ]:
def sum(x,w):
  return (np.dot(x,w))

In [ ]:
#online learning
epochs = 1
eta = 0.01 #0.001
e = 0
while e<epochs:
  epoch_loss = 0.0
  for i in range(len(x_train)):
    yhat = sum(x_train[i],weights) + bias 
    diff = yhat-y_train[i]
    # print(yhat)
    # print(y_train[i])
    loss = (diff**2)
    for j in range(len(weights)):
      gradient = diff*x_train[i][j]
      weights[j] = round(weights[j] - (eta*gradient),3)
    bias = round(bias - (eta*diff),3)
    print(weights)
    epoch_loss = epoch_loss + loss
  e += 1
  if e == 1: 
    print("Initial loss: ", epoch_loss/len(x_train))
  if e == epochs:
    print("Final loss: ", epoch_loss/len(x_train))

[1.37, 1.554]
[0.769, -0.851]
[0.765, -0.851]
[0.7, -0.895]
[0.653, -1.082]
[0.361, -1.422]
Initial loss:  167.74286779489455
Final loss:  167.74286779489455


In [ ]:
print(weights)

[0.361, -1.422]


In [ ]:
print(bias)

0.468


In [ ]:
def floattoint64(x):
		x = np.uint64((1<<16)*(x))
		return x

for i in range(2):
  weights[i] = floattoint64(weights[i])

In [ ]:
print(weights)

[23658, 18446744073709458424]


In [ ]:
#batch learning
# epochs = 0
# eta = 0.001
# total_epochs=5
# w=[0,0,0,0,0,0,0,0,0,0,0,0,0]
# while epochs<total_epochs:
#   epoch_loss = 0.0
#   for i in range(len(x_train)):
#     yhat = sum(weights,x_train[i]) 
#     diff = y_train[i] - yhat 
#     loss = (diff**2)
#     for j in range(len(weights)):
#       gradient = -2*diff*x_train[i][j]
#       w[j] = w[j] + gradient

#     epoch_loss = epoch_loss + loss
#   weights = weights - np.multiply(eta/len(x_train),w)
#   epochs += 1
#   if epochs == 1: 
#     print("Initial loss: ", epoch_loss/len(x_train))
#   elif epochs == total_epochs:
#     print("Final loss: ", epoch_loss/len(x_train))

In [ ]:
# epochs = 0
# eta = 0.001
# while epochs<10:
#   for i in range(len(x_train)):
#     yhat = sum(x_train[i],weights) 
#     diff = (yhat-y_train[i])
#     for j in range(13):
#       weights[j] = weights[j] - (eta*diff*x_train[i][j])
#     # np.round(weights, 8)
#     loss = 0.0
#     for k in range(len(x_train)):
#       diff2 = ((sum(x_train[k],weights) - y_train[k])**2)/len(x_train)
#       loss = loss + (diff2)
#   # loss = round(loss,4)
  
#   epochs += 1
#   # if epochs == 0: 
#   #   print("Initial loss: ", loss)
#   # elif epochs == 1:
#   #   print("Final loss: ", loss)

In [ ]:
# epochs = 0
# eta = 0.001
# while epochs<10:
#   loss = 0.0
#   for i in range(len(x_train)):
#     yhat = np.dot(weights,x_train[i]) 
#     diff = yhat-y_train[i]
#     loss = loss + ((diff**2)/len(x_train))
#     # print(x_train[i])
#     for j in range(13):
#       gradient= gradient+2*diff*x_train[i][j]   
#       weights[j] = weights[j] - (eta*(gradient/len(x_train)))

#   epochs=epochs+1
   
#   print('Loss for epoch is: ',loss/len(x_train))

In [ ]:
#checking something - helper function
def mul(a,b):
  m = np.multiply(a,b)
  print(m)  
  print(m.shape)
  print(np.subtract(np.array([-21,1,-11]),m))

In [ ]:
mul(-3.4,[101,192,123])

[-343.4 -652.8 -418.2]
(3,)
[322.4 653.8 407.2]


In [ ]:
np.multiply(2,[-13.23,-0.723,1.38]) - [1,2,3]

array([-27.46 ,  -3.446,  -0.24 ])